### ISSUE TITLE
[Question] Is there a way to extract keys from custom message declarations?

### ISSUE THREAD

**Issue by willross** [hjylewis/babel-plugin-inline-i18n-messages#10]
This is not a problem with this library. I see that it is using `@formatjs/cli` which is in turn using `babel-plugin-react-intl` to extract keys for each page, and `babel-plugin-react-intl` *only* extracts keys for `defineMessages()`, `defineMessage()`, and `<FormattedMessage>` imported from `react-int` and declared according to `react-intl`'s API.

However, many developers, myself included, find those declarations overly verbose and use something like
```
// translate.js

export default const t = (id) => ( <FormattedMessage id={id} /> )
```
and then elsewhere in code
```
// app.js

import t from "./translate"
...
<span>{t("hello")}</span>
```
And so those declarations don't get extracted.

So the question is - is there a way to extract such declarations?

**Comment by hjylewis** [comment]
> is there a way to extract such declarations?

For sure. This plugin actually gives the user control over how to extract the keys through the `extractKeysFile` option. Using `@formatjs/cli` is just a built-in default.

https://github.com/hjylewis/babel-plugin-inline-i18n-messages#extractkeys

Just define a function `extractKeys` function that works with your set up. In this case you'd want to parse the given file into an AST and look for a call expression of `t` from your `translate` module. Or use something simpler like regex.

Does that answer your question?

**Comment by willross** [comment]
I see, thanks! I've never written a babel plugin before, but I'll look into it.

**Comment by hjylewis** [comment]
I would recommend astexplorer.net as a tool: https://astexplorer.net/#/gist/aa353a428a70e26aabc120dbbaf65126/988ede14a72803e8f4bef9b5652858dc29c5f0bb

**Comment by willross** [comment]
That's a great tool, many thanks!
