### ISSUE TITLE
Error if message is ALLCAPS

### ISSUE THREAD

**Issue by willross** [hjylewis/babel-plugin-inline-i18n-messages#9]
If a message is in all caps (e.g. `"FAQ"`) or a message ID is in all caps/number (e.g. `"404"`) the following error is thrown by Babel:

```
Error: @babel/template placeholder "FAQ": Expected string substitution
```

While changing message ID's to something else is not a problem, messages themselves shouldn't trigger such an error.

Is there a way to fix that?

**Comment by willross** [comment]
Adding a `placeholderPattern: false` to `template`'s options helps (https://github.com/babel/babel/issues/8067)

**Comment by hjylewis** [comment]
Nice catch! Feel free to open a PR and add a test. Otherwise, I'll get around to it.
